In [312]:
import numpy as np
data = np.loadtxt("/Users/mariya/pers/Learnings/Python/Scaler Notes/Common Core/fitness copy.txt", dtype='str')



In [313]:
# Concatenate
a = np.arange(1, 5)
b = np.arange(1, 5)

np.concatenate([a, b])


array([1, 2, 3, 4, 1, 2, 3, 4])

# np.argsort() gives the indexes
# np.argmin() returns the min value of index
# np.argmax() returns the max value of index
# np.unique() 
# np.mean()
# np.matmul() OR np.dot() OR m%n are used for matrix multiplication
# np.vectorize()
# np.tile() duplicates the given matrix
# 1d array is considered as Vector, so np.concatenate doesn't work for 1d array
# np.hstack adds two arrays horizontally 
# np.vstack adds two arrays vertically
# Concatenate, hstack & vstack almost same in terms of operations; the only difference b/w Concatenate and h or vstacks is - Conceatenate doesn't work on 1d array; but h & v stacks work even for 1d array. But for all three functions, the matrix dimenstions must be MxN and NxM format.
# np.split() splits the given array, np.hsplit() 

In [314]:
d = np.arange(1, 13)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [315]:
np.split(d, 2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [316]:
np.split(d, 12)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [317]:
x = np.arange(1, 5)
print(x)
x += 2
print(x)

[1 2 3 4]
[3 4 5 6]


# we can apply following functions with this data set
# np.mean(step_count)
# np.argmax(step_count)
# np.argmin(step_count)
# np.unique() returns the list of categories

In [318]:
import numpy as np
data = np.loadtxt("/Users/mariya/pers/Learnings/Python/Scaler Notes/Common Core/fitness copy.txt", dtype='str')
data = data.T
date, step_count, mood, calories_burnt, hours_of_sleep, bool_active, weight = data
step_count = np.array(step_count, dtype="int")
calories_burnt=np.array(calories_burnt, dtype="int")
hours_of_sleep = np.array(hours_of_sleep, dtype="int")
weight = np.array(weight, dtype="int")
date_when_high_step_count = date[step_count.argmax()]
print(f"Date when Max Step Count: {date_when_high_step_count}")
date_when_low_step_count = date[np.argmin(step_count)]
print(f"Date when Min Step Count: {date_when_low_step_count}")


Date when Max Step Count: 14-12-2017
Date when Min Step Count: 08-10-2017


In [319]:
mood[mood=="300"]="Happy"
mood[mood=="200"]="Neutral"
mood[mood=="100"]="Sad"

In [320]:
mood_when_max_step_count = mood[np.argmax(step_count)]
print(f"Mood of the person when Max Step Count: {mood_when_max_step_count}")
mood_when_min_step_count = mood[np.argmin(step_count)]
print(f"Mood of the person when Min Step Count: {mood_when_min_step_count}")

Mood of the person when Max Step Count: Happy
Mood of the person when Min Step Count: Sad


In [321]:
mood_when_max_cal_burnt = mood[np.argmax(calories_burnt)]
print(f"Mood when Max Calories Burnt: {mood_when_max_cal_burnt}")

Mood when Max Calories Burnt: Happy


In [322]:
temp = np.mean(step_count[mood=="Sad"])
temp

2103.0689655172414

In [323]:
avg_step_count_on_sad = np.mean(step_count[mood=="Sad"])
avg_step_count_on_sad

2103.0689655172414

In [324]:
max_cal_burnt_when_happy = np.argmax(calories_burnt[mood=="Happy"])
calories_burnt[max_cal_burnt_when_happy]

137

In [325]:
min_cal_burnt_when_sad = np.argmin(calories_burnt[mood=="Sad"])
calories_burnt[min_cal_burnt_when_sad]

197

In [326]:
max_step_count_when_happy = np.argmax(step_count[mood=="Happy"])
step_count[max_step_count_when_happy]

4033

In [327]:
min_step_count_when_sad = np.argmin(step_count[mood=="Sad"])
step_count[min_step_count_when_sad]

6041

In [328]:
np.unique(mood, return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [329]:
category, count = np.unique(bool_active, return_counts=True)
print(np.asarray((category, count)).T)


[['0' '54']
 ['500' '42']]


In [330]:
bool_active

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [331]:
bool_active[bool_active=="0"]="Inactive"
bool_active[bool_active=="500"]="Active"
bool_active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [332]:
active_categories = np.unique(bool_active, return_counts=True)
active_categories

(array(['Active', 'Inactive'], dtype='<U10'), array([42, 54]))

In [333]:
unique, counts = np.unique(mood, return_counts=True) 
print(np.asarray((unique, counts)).T)

[['Happy' '40']
 ['Neutral' '27']
 ['Sad' '29']]


In [334]:
avg_step_count_when_happy = np.mean(step_count[mood=="Happy"])
avg_step_count_when_happy

3392.725

In [335]:
more_than_4000Steps = np.unique(mood[step_count>4000], return_counts=True)
print(np.asarray(more_than_4000Steps).T)


[['Happy' '22']
 ['Neutral' '9']
 ['Sad' '7']]


# Some Insigths to derive:
<!-- 1. Is there a correlation b/w Mood and the calories_burnt? If yes, what's the mood of the person when he burns more calories?
2. What's the correlation b/w Mood and the hours_of_sleep? Is a particular Mood impacts the hours of sleep?
3. Though the person is consistently doing workout, weight hasn't reduced drastically, why? -->

In [336]:
# Max calories burnt when is Happy
max_cal_burnt_when_happy = np.max(calories_burnt[mood=="Happy"])
print(max_cal_burnt_when_happy)


243


In [337]:
# Mood when min calories burnt
mood[np.argmin(calories_burnt)]

'Sad'

In [338]:
# Max hours of Sleep and corresponding Mood

max_hours_of_sleep = np.max(hours_of_sleep)
mood_when_sleep_more = mood[np.argmax(hours_of_sleep)]
print(f"Maximum hours of Sleep: {max_hours_of_sleep}")
print(f"Mood, when he sleeps more: {mood_when_sleep_more}")


Maximum hours of Sleep: 9
Mood, when he sleeps more: Happy


In [339]:
# Min hours of sleep and corresponding Mood

min_hours_of_sleep = np.min(hours_of_sleep)
mood_when_sleeps_less = mood[np.argmin(hours_of_sleep)]
print(f"Minimum hours of sleep: {min_hours_of_sleep}")
print(f"Mood, when sleeps less: {mood_when_sleeps_less}")

Minimum hours of sleep: 2
Mood, when sleeps less: Happy


In [340]:
np.histogram2d(hours_of_sleep, weight)

(array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [13.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [30.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.],
        [11.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  2.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 4.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
        [ 7.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  1.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]),
 array([2. , 2.7, 3.4, 4.1, 4.8, 5.5, 6.2, 6.9, 7.6, 8.3, 9. ]),
 array([64. , 64.2, 64.4, 64.6, 64.8, 65. , 65.2, 65.4, 65.6, 65.8, 66. ]))

In [341]:
bool_active[bool_active=="1"]="Active"
bool_active[bool_active=="0"]="Inactive"
bool_active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [342]:
temp = np.unique(bool_active, return_counts=True)
print(np.asarray(temp).T)

[['Active' '42']
 ['Inactive' '54']]


In [343]:
# mood[np.unique(bool_active, return_counts=True)]    # to calculate the mood count based on Active/Inactive state 

moods_when_active = np.unique(mood[bool_active=="Active"], return_counts=True)
moods_when_not_active = np.unique(mood[bool_active=="Inactive"], return_counts=True)
print("Mood when Active:")
print(np.asarray(moods_when_active).T)
print("Mood when Inactive")
print(np.asarray(moods_when_not_active).T)

Mood when Active:
[['Happy' '24']
 ['Neutral' '14']
 ['Sad' '4']]
Mood when Inactive
[['Happy' '16']
 ['Neutral' '13']
 ['Sad' '25']]


In [344]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


In [345]:
np.max(a)

9

In [346]:
np.max(a, axis=1)

array([3, 6, 9])

In [347]:
np.max(a, axis=0)

array([7, 8, 9])

In [348]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [349]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [350]:
def cube(s):
    return s**3
print(cube(arr))

[   1    8   27   64  125  216  343  512  729 1000 1331 1728]


In [351]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [352]:
arr1 = arr.reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [353]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [354]:
arr1 = arr1.reshape(3, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [355]:
np.tile(arr1, (2,2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [356]:
np.tile(arr1, (3, 4))

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])

In [357]:
# Quiz Qn #1 to test np.all

m = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

n = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
)
print(np.all(m==n))


True


In [358]:
# Quiz Qn #2 to test np.any

m = np.array([[1, 2, 3],
            [4, 6, 6],
            [7, 8, 9]])

n = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
)
print(np.any(m>n))

True


In [359]:
# Quiz Qn #3 

x = [1, 2, 3]
y = [3, 4, 5]

print(x>=y)

False


In [360]:
# Quiz Qn #3.1 Check the difference b/w this one and the above one

x = np.array([1, 2, 3])
y = np.array([3, 4, 5])

print(x>=y)

[False False False]


In [361]:
# Simple np sorting; by default axis value is 1 which is horizontal sorting

someArray = np.array([
    [21, 12, 32],
    [4, 56, 30],
    [75, 3, 10]]
)
np.sort(someArray)

array([[12, 21, 32],
       [ 4, 30, 56],
       [ 3, 10, 75]])

In [362]:
# axis = 0 is vertical sorting

np.sort(someArray, axis=0)

array([[ 4,  3, 10],
       [21, 12, 30],
       [75, 56, 32]])

In [363]:
m

array([[1, 2, 3],
       [4, 6, 6],
       [7, 8, 9]])

In [364]:
# Max value from the whole array
print(np.max(m))

9


In [365]:
# Max value from the whole array but column-wise (vertically)
print(np.max(m, axis=0))

[7 8 9]


In [366]:
# Max value from the whole array but row-wise (Horizontally)
print(np.max(m, axis=1))

[3 6 9]


In [369]:
# Quiz Qn#5 
i = np.array([1, 2, 3, 4, 5])
j = np.array([0, 3, 2, 4, 1])
k = i+j
k = k*i
print(k[2])

15
